default:
  image: docker:latest
  tags:
    - shell

build-job:
  stage: build
  script:
    - docker compose build
  only:
    - main

test-job1:
  stage: test
  script:
    - echo "This job tests something"
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - echo $DOTENV | tr " " "\n" > .env
    - docker compose up -d --force-recreate
  only:
    - main
