default:
  image: docker:latest
  tags:
    - shell

build-job:
  stage: build
  script:
    - docker compose build -e DOTNEV=$DOTNEV
  only:
    - main

test-job1:
  stage: test
  script:
    - echo "This job tests something"
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - docker compose up -d --force-recreate -e DOTNEV=$DOTNEV
  only:
    - main
