version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${BE_PORT}:${BE_PORT}
    depends_on: 
      - db
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:$5432/${DB_NAME}
      PORT: ${BE_PORT}
      SESSION_SECRET: ${SESSION_SECRET}
      NODE_ENV: ${ENVIRONMENT}


  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
    ports:
      - ${FE_PORT}:5173
    environment:
      BE_ADDRESS: ${BE_HOST}

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
